certManager:
  enabled: true

webhook:
  caBundle: blahblahblah

  namespaceSelector:
    matchExpressions:
      - key: c7n-monitor
        operator: NotIn
        values: ["false"]
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      operations: ["CREATE"]
      resources: ["pods"]
      scope: Namespaced

policies:
  source: "configMap"
  configMap:
    policies:
      - name: missing-recommended-labels
        mode:
          type: k8s-admission
          on-match: deny
          operations:
            - CREATE
            - UPDATE
        resource: k8s.pod
        filters:
          - or:
            - metadata.labels."app.kubernetes.io/name": absent
            - metadata.labels."app.kubernetes.io/instance": absent
            - metadata.labels."app.kubernetes.io/version": absent
            - metadata.labels."app.kubernetes.io/component": absent
            - metadata.labels."app.kubernetes.io/part-of": absent
            - metadata.labels."app.kubernetes.io/managed-by": absent
  volumeMount:
    readOnly: true

controller:
  image: localhost:5001/c7n-kube:0.9.19.0-16-gf7cae659b-dirty
