

---

apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: create-namespace
deploy:
  kubectl:
    manifests:
      - .skaffold/namespace.yaml

---
apiVersion: skaffold/v2beta29
kind: Config
requires:
  - configs: [create-namespace]
metadata:
  name: deploy
build:
  artifacts:
  - context: ../../
    docker:
      dockerfile: ../../docker/c7n-kube
    image: c7n-kube

deploy:
  kubectl:
    defaultNamespace: c7n-system
    manifests:
      - .skaffold/templates/*.yaml

  helm:
    releases:
      - artifactOverrides:
          image: c7n-kube
        chartPath: ../../../c7n-helm-charts/c7n_kube/
        imageStrategy:
          fqn: {}
        name: c7n-kube
        namespace: c7n-system
        valuesFiles:
          - .skaffold/values.yaml
