name: "Docker Build CI"
on:
  push:
    branches:
      - docker-buildx4
  pull_request:
    branches:
      - docker-buildx4
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: c7n build and test
        uses: ./.github/composites/docker-build-push
        env:
          HUB_USER: sonnyshi
          HUB_TOKEN: ${{ secrets.DOCKER_CI_HUB_TOKEN }}
        with:
          name: c7n
          push: true
          platforms: linux/amd64
          repository: sonnyshi
