name: "Docker Build"

on:
  push:
    branches:
      - multi-arch-dockerbuild
    tags:
      # todo: update for 1.0
      - 0.*

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Docker Build Env
        # bin directory is in .dockerignore
        run: |
          python -m pip install --upgrade pip
          pip install docker click pytest pyyaml six
          mkdir -p bin
          wget -q -O bin/trivy.tgz https://github.com/aquasecurity/trivy/releases/download/v0.5.4/trivy_0.5.4_Linux-64bit.tar.gz
          cd bin && tar xzf trivy.tgz

      # Ubuntu images
      - name: cli
        env:
          HUB_USER: sonnyshi
          HUB_TOKEN: ${{ secrets.DOCKER_CI_HUB_TOKEN }}
        run: |
          python tools/dev/dockerpkg.py build -v --test --scan --push -t auto -r sonnyshi -i cli

      - name: org
        env:
          HUB_USER: sonnyshi
          HUB_TOKEN: ${{ secrets.DOCKER_CI_HUB_TOKEN }}
        run: |
          python tools/dev/dockerpkg.py build -v --test --scan --push -t auto -r sonnyshi -i org

      - name: mailer
        env:
          HUB_USER: sonnyshi
          HUB_TOKEN: ${{ secrets.DOCKER_CI_HUB_TOKEN }}
        run: |
          python tools/dev/dockerpkg.py build -v --test --scan --push -t auto -r sonnyshi -i mailer

      - name: policystream
        env:
          HUB_USER: sonnyshi
          HUB_TOKEN: ${{ secrets.DOCKER_CI_HUB_TOKEN }}
        run: |
          python tools/dev/dockerpkg.py build -v --test --scan --push -t auto -r sonnyshi -i policystream
